// The compiler layer. Independent of the runtime — reads content/**/*.md and
// emits src/generated/content.ts as a structured manifest. Run via
// `npm run build:content` or automatically by the content-plugin.
//
// Source markdown is pure content: a `# Title` and a body. Nothing else — no
// frontmatter, no shebang, no type markers. The compiler ALONE decides what each
// document becomes (a static page, an executable TUI app, ...). Today that
// decision is a trivial rule (everything is a page); the `analyze()` hook is
// where a future LLM-driven pass will turn a document's body into a prompt and
// decide its kind and any generated artifacts.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, basename, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AppDecl, Document, Manifest } from '../src/content/types';
import { expandMacros } from './macros';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const CONTENT_DIR = join(ROOT, 'content');
const OUT_FILE = join(ROOT, 'src', 'generated', 'content.ts');

/** Recursively collect *.md files under dir. */
function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (entry.endsWith('.md')) acc.push(p);
  }
  return acc;
}

function extractTitle(body: string): string | undefined {
  const m = body.match(/^#\s+(.+)$/m);
  return m?.[1].trim();
}

/**
 * Decide a document's kind and any artifacts to generate. Placeholder for a
 * future LLM-driven pass: the body is the prompt; the model decides whether this
 * is a static page or an executable app. For now, everything renders as a page.
 */
function analyze(_body: string): { kind: string; apps: AppDecl[] } {
  return { kind: 'page', apps: [] };
}

function buildDoc(file: string): Document {
  const body = expandMacros(readFileSync(file, 'utf8').trim());
  const path = relative(CONTENT_DIR, file).replace(/\\/g, '/');
  const slug = path.replace(/\.md$/, '');
  const { kind, apps } = analyze(body);
  return {
    slug,
    title: extractTitle(body) ?? slug,
    body,
    path,
    kind,
    apps,
  };
}

export async function buildContent(): Promise<Manifest> {
  const docs = walk(CONTENT_DIR).map(buildDoc);

  const seen = new Set<string>();
  for (const d of docs) {
    if (seen.has(d.slug)) throw new Error(`duplicate slug "${d.slug}" (${d.path})`);
    seen.add(d.slug);
  }

  docs.sort((a, b) => a.slug.localeCompare(b.slug));
  const apps = docs.flatMap((d) => d.apps);
  const manifest: Manifest = { documents: docs, apps };

  const out =
    '// AUTO-GENERATED by scripts/build-content.ts — do not edit by hand.\n' +
    "import type { Manifest } from '../content/types';\n\n" +
    `export const manifest: Manifest = ${JSON.stringify(manifest, null, 2)};\n`;
  writeFileSync(OUT_FILE, out);

  return manifest;
}

// CLI entry: `tsx scripts/build-content.ts`
const invokedDirectly = basename(process.argv[1] ?? '') === 'build-content.ts';
if (invokedDirectly) {
  buildContent().then((m) => {
    console.log(
      `content: ${m.documents.length} document(s) -> src/generated/content.ts`,
    );
  });
}
